### ISSUE TITLE
missed heartbeat from celery - PiWind Analysis Fails

### ISSUE THREAD

**Issue by maymish2023** [OasisLMF/OasisPlatform#1013]
## Issue Description
I am using Oasis Platform Evaluation to test my installation by running a PiWind analysis but the analysis fails. The import happens successfully and generates import summary as well.

## Steps to Reproduce
I followed the steps suggested in https://www.youtube.com/watch?v=SxRt5E-Y5Sw

## Version / Environment information
OS: Sonoma 14.3.1 (23D60) on Apple M1 Max
coreoasis/model_worker:2.3.1
coreoasis/api_server:2.3.1
coreoasis/oasisui_app:1.11.7
OasisLMF | PiWind | v2

## Example data / logs
Input file used: /OasisEvaluation/OasisPiWind/exposure_data/SourceLocOEDPiWind10.csv

[piwindv2_analysis_log_20240329.txt](https://github.com/OasisLMF/OasisPlatform/files/14808555/piwindv2_analysis_log_20240329.txt)
<img width="1352" alt="image" src="https://github.com/OasisLMF/OasisPlatform/assets/165426285/118208c6-f997-4cda-9c7e-978623ede0d9">

**Comment by sambles** [comment]
Hello @maymish2023  

I think the analysis failing is due to memory pressure. The missed heartbeat messages are likely a symptom of that issue. 
```
2024-03-29 16:07:05 v2-worker-1           | Traceback (most recent call last):
2024-03-29 16:07:05 v2-worker-1           |   File "/home/worker/.local/lib/python3.10/site-packages/billiard/pool.py", line 1264, in mark_as_worker_lost
2024-03-29 16:07:05 v2-worker-1           |     raise WorkerLostError(
2024-03-29 16:07:05 v2-worker-1           | billiard.exceptions.WorkerLostError: Worker exited prematurely: signal 9 (SIGKILL) Job: 24.
```
From this trace, I suspect the system ran out memory and killed the worker mid execution. 

To test that try limiting the number of concurrent execution chunks to a low number. For A `v2` you can set this value using swagger:
![Screenshot from 2024-04-02 11-28-16](https://github.com/OasisLMF/OasisPlatform/assets/9889973/b10dc6b1-ceeb-46f8-b8d0-78ac8c2a6335)

**Comment by benhayes21** [comment]
Hi @maymish2023 - let us know if this works for you. We'll close the issue off in 7 days if we don't hear anything else
