### ISSUE TITLE
Better handling of 'No Keys data' errors 

### ISSUE THREAD

**Issue by sambles** [OasisLMF/OasisPlatform#391]
* On Generate Inputs errors, store the run directory for debugging 
* Store the **keys-error.csv** and exposure summary files in the API

**Comment by aiste-kalinauskaite** [comment]
I have tested this on one of the models, and it returns status "Failed" and there is no keys-error.csv file. I have used the wrong country and left Lat/long = 0 in the hope that this would force the model to be outside the model domain.

**Comment by benhayes21** [comment]
It sounds like this might be more of an issue with the keys lookup service in question rather than oasislmf. If the keys server does not return anything and fails out, then there will be no keys error file. Can you let us know which model it is and we can work out how it handles countries and lat/longs which it does not recognise please?

**Comment by benhayes21** [comment]
suggest better error catching
