### ISSUE TITLE
Incorrect AWS_LOCATION key used for worker files

### ISSUE THREAD

**Issue by johanxnilsson** [OasisLMF/OasisPlatform#423]
This might not be an issue but wanted to ask the question anyway. Sam kindly patched 1.11.1 on friday to repair an S3 storage issue:

coreoasis/model_worker:1.11.2-alpha
coreoasis/api_server:1.11.2-alpha

I noticed however that files previously stored in client AWS_LOCATION (input, output, log tar.gz files for example) now are stored to the server AWS_LOCATION. Maybe a mix up in the alpha or are all files are stored in the same AWS_LOCATION now?

**Comment by sambles** [comment]
Pasting here for ref:

> **What should happen is:**
worker uploads shared files to the values set for the worker and hands over that reference to the worker-monitor
the monitor then takes that S3 ref, either URL or object key, and loads it into the server's storage space
Otherwise the server might run into trouble if it doesn't know the value of  AWS_LOCATION  set in the worker.

Closing issue
