### ISSUE TITLE
Investigate stuck analysis (exit handler OOM Trap)  

### ISSUE THREAD

**Issue by sambles** [OasisLMF/OasisPlatform#675]
## Issue Description
Report of an analysis getting stuck (zombie worker) after out of memory kill on fmpy

**Comment by sambles** [comment]
okey that is interesting, checking this locally. I see two celery process per worker 

```
$ celery --app src.model_execution_worker.tasks worker --concurrency=1 --loglevel=INFO -Q "FOO-BAR-1" |& tee -a /var/log/oasis/worker.log
```
```
$ ps aux | grep FOO-BAR-1                                                    ✔ 
sam       114114  5.1  0.2  93736 69888 pts/9    S+   16:57   0:00 /home/sam/repos/venv/api/bin/python3.9 /home/sam/repos/venv/api/bin/celery --app src.model_execution_worker.tasks worker --concurrency=1 --loglevel=INFO -Q FOO-BAR-1
sam       114117  0.1  0.1  93320 62152 pts/9    S+   16:57   0:00 /home/sam/repos/venv/api/bin/python3.9 /home/sam/repos/venv/api/bin/celery --app src.model_execution_worker.tasks worker --concurrency=1 --loglevel=INFO -Q FOO-BAR-1
   ... 
```

* **(Case 1)** Killing the parent celery process
Running `$ kill -9 114114` should kill the main celery causing the worker to exit 

* **(Case 2)** Killing the child celery process 
After running `$ kill -9 114117` I see this in the celery logs
```
[2022-09-14 16:57:38,065: INFO/MainProcess] Events of group {task} enabled by remote.
[2022-09-14 16:59:22,290: ERROR/MainProcess] Process 'ForkPoolWorker-1' pid:114117 exited with 'signal 9 (SIGKILL)'

```
Followed by a new process spawning
```
$ ps aux | grep FOO-BAR-1                                                    ✔ 
sam       114114  0.2  0.2  95324 71456 pts/9    S+   16:57   0:01 /home/sam/repos/venv/api/bin/python3.9 /home/sam/repos/venv/api/bin/celery --app src.model_execution_worker.tasks worker --concurrency=1 --loglevel=INFO -Q FOO-BAR-1
sam       114573  0.0  0.1  95860 63728 pts/9    S+   16:59   0:00 /home/sam/repos/venv/api/bin/python3.9 /home/sam/repos/venv/api/bin/celery --app src.model_execution_worker.tasks worker --concurrency=1 --loglevel=INFO -Q FOO-BAR-1
```

Are you seeing the worker hang after the **2nd** case?  

I'll need to do some more digging, thanks for the pointer @JCrane512 !

**Comment by JCrane512** [comment]
So what I am actually investigating is a related bug, I found this ticket looking for one about something similar. 

We are seeing a similar problem (also this one), where processes are killed due to an out-of-memory issue. However, the analysis still completes successfully with only partial results. I am as of yet unsure if this is a problem occurring in Oasis's code or our own. This specific issue appears to need multiple processes to be killed in a specific order by the OOM killer. If you have seen this before or have any information about it that would be amazing!

I can confirm I see the worker hang when a celery task is killed via `$ kill -9 <task_id>`. I am 80% sure it is the second case you are describing, as I see the celery process restart. It is worth noting that the task will hang regardless of if it is killed with `SIGKILL` or with `SIGTERM`.

I can also add that if any of our loss calculation processes (`JBA_FLY_gulcalc`) are killed by the OOM killer and they die first. The analysis will correctly crash. If they are killed after a celery worker results are variable, and I have not properly tested it. 

Also as a point of interest, there are 4 zombie processes hanging around after a successful analysis is run through our internal Loss Model UI. When the OOM killer kills a task there is normally around 30 zombie processes, but this is not really a surprise. I will show them below (farm is a username). I am unsure what the bash processes relate to, they could be internal, but I believe the `ktools_monitor.` is Oasis's. 

```shell
$ ps aux | grep farm | sort -k 8 
farm     32403  0.0  0.0      0     0 ?        Z    14:06   0:00 [bash] <defunct>
farm     32405  0.0  0.0      0     0 ?        Z    14:06   0:00 [bash] <defunct>
farm     32408  0.0  0.0      0     0 ?        Z    14:06   0:00 [ktools_monitor.] <defunct>
farm      2829  0.0  0.0      0     0 ?        Z    14:07   0:00 [sleep] <defunct>
```

**Comment by sambles** [comment]
Marking this as closed by https://github.com/OasisLMF/OasisLMF/pull/1192 in `1.27.0`
